### ISSUE TITLE
Create a new tutorial

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/theia-tutorial-extension#41]
I wanted to create a new tutorial from scratch.
So I downloaded the vsix file and installed it into VSCode.
Now I was stuck ;-) 
My questions are:
- is there a special folder (eg `.tutorial`) I need to put my new file into?
- do I need to follow name conventions (it seems like I have to, eg `foo.tut.json`)
- is there autocompletion for the json or do I need to 'know' what I have to write there?
Or is there a yeoman generator that I can use to get me kick started?

FYI, I downloaded the https://github.com/eclipsesource/theia-tutorial-extension/blob/main/schema/tutorial.json and configured my workspace to use it as the schema for all my `*.tut.json` files, but the schema seems to be outdated as this json: https://github.com/eclipsesource/glsp-tutorial/blob/main/.tutorial/glsp.tut.json shows warnings on the `typeId` property ...

Any help is appreciated ...

**Comment by eneufeld** [comment]
Could you explain what the `assistance` action is and how to use it, I can't find any example for this

**Comment by max-elia** [comment]
> * is there a special folder (eg `.tutorial`) I need to put my new file into?
> * do I need to follow name conventions (it seems like I have to, eg `foo.tut.json`)

This repo's main output is the extension, which reads any `*.tut.json` file in the workspace and loads the tutorial defined in it. The `.tutorial` folder is used to have all tutorial-related files (such as solution-files, tests and workspace-backups) in one place, but the tutorial will also be loaded if placed outside the folder.

> * is there autocompletion for the json or do I need to 'know' what I have to write there?

- Autocompletion can be configured in VSCode by adding:
`"json.schemas": [
    {
      "fileMatch": [
        "/*.tut.json"
      ],
      "url": "./schema/tutorial.json"
    }
  ]`
to the file `.vscode/settings.json`

> FYI, I downloaded the https://github.com/eclipsesource/theia-tutorial-extension/blob/main/schema/tutorial.json and configured my workspace to use it as the schema for all my `*.tut.json` files, but the schema seems to be outdated as this json: https://github.com/eclipsesource/glsp-tutorial/blob/main/.tutorial/glsp.tut.json shows warnings on the `typeId` property ...

The `typeId` is indeed not needed anymore, since it was used for the tree-based tutorial-generator which is not used anymore.

**Comment by max-elia** [comment]
> Could you explain what the `assistance` action is and how to use it, I can't find any example for this

`assistance` is a theia extension which shows an arrow pointing to given id's inside a theia instance. It is actually a feature specific to the GLSP tutorial: https://github.com/eclipsesource/glsp-tutorial where it is injected into the exercise build.
Therefore it is not anymore included in this tutorial-extension, although it is still in the repo. It should be moved to a dedicated repository.
https://github.com/eclipsesource/glsp-tutorial/issues/5
